#ifndef LOAD_VERSION_HPP_
#define LOAD_VERSION_HPP_

#define LOAD_VERSION_MAJOR @libload_VERSION_MAJOR@
#define LOAD_VERSION_MINOR @libload_VERSION_MINOR@
#define LOAD_VERSION_PATCH @libload_VERSION_PATCH@

#endif